name: BlockRanks
main: me.crosant.blockranks.BlockRanks
version: 0.0.1
commands:
    Ranks:
          description: BlockRanks
          usage: /<command> arg
permissions:
  BlockRanks.*:
    description: Gives access to all BlockRanks commands
    children:
      BlockRanks.reload: true
      BlockRanks.purge: true
      BlockRanks.set: true
  BlockRanks.reload:
     description: BlockRanks Reload
  BlockRanks.purge:
     description: BlockRanks Purge
  BlockRanks.set:
     description: BlockRanks Set
depend: [Vault]