name: TimeRanks
main: me.crosant.timeranks.TimeRanks
version: 0.0.1
commands:
    Ranks:
          description: TimeRanks
          usage: /<command> arg
permissions:
  TimeRanks.*:
    description: Gives access to all TimeRanks commands
    children:
      TimeRanks.reload: true
  TimeRanks.reload:
     description: TimeRanks Reload
depend: [Vault]